name: city_traffic
version: "1.0.0"
config-version: 2

profile: city_traffic

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages

models:
  city_traffic:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

vars:
  deploy_env: "{{ env_var('DEPLOY_ENV', 'dev') }}"
